### ISSUE TITLE
Incongruencias entre búsquedas y RSS generado

### ISSUE THREAD

**Issue by afcj** [tanrax/wallaviso#1]
Hola Andros, he hecho una busqueda de "warhammer", distancia 400 (que entiendo que es 400 o más) y precio mínimo 2, lo que a nivel de interfaz web en www.wallaviso.com me da 5 resultados (los 5 primeros que en wallapop aparecen si hago esa busqueda y ordeno por Novedades).

Hasta ahí todo correcto aunque no estaría mal poder ordenar al gusto, sin embargo el RSS generado http://www.wallaviso.com/rss/703 contiene 40 resultados entre los que **no se encuentran** los 5 anteriores. No se a que criterios responden.

A parte creo que habría que suprimir la obligatoriedad de meter el código postal y ciudad, ya que en la API de Wallapop no son obligatorios.

**Comment by tanrax** [comment]
Puede ser que Wallapop haya incluido algún cambio en su código. Habría que revisar si solo te esta ocurriendo a tí o es un problema general. Lamentablemente ya no ofrezco mantenimiento, lo siento. Puedes ver mis razones [aquí](https://programadorwebvalencia.com/wallaviso-por-que-no-funciono-un-servicio-de-avisos-para-wallapop/). Si sabes programar, encantado estaré de aceptar tu parche. Un saludo!
