### ISSUE TITLE
no funciona?

### ISSUE THREAD

**Issue by quarkpower** [tanrax/wallaviso#5]
Esta app no funciona actualmente, verdad? en la versión web realizo búsquedas (que sé que hay anuncios publicados para mostrar) e indica que no existe ningún artículo, aunque se encuentre dentro de la distancia establecida.

**Comment by tanrax** [comment]
Necesita mantenimiento. Cualquier Pull requests será bien recibida :)

**Comment by quarkpower** [comment]
te refieres a un pago? es difícil pensar en ello sin siquiera poder probar el producto

**Comment by tanrax** [comment]
La plataforma es Opensource. Aquí tienes el código.

**Comment by tanrax** [comment]
Me refiero que puedes estudiar el código y aportar actualizaciones.
Un saludo

**Comment by quarkpower** [comment]
discúlpame, my python no es muy allá pero le echaré un ojo a ver

**Comment by tanrax** [comment]
> 
> 
> discúlpame, my python no es muy allá pero le echaré un ojo a ver

Perfecto!
